function stat(label,value){const d=document.createElement('div');d.className='bb-stat';const b=document.createElement('strong');b.textContent=value;const s=document.createElement('span');s.textContent=label;d.append(b,s);return d}
function categoryCard(c){const a=document.createElement('a');a.className='bb-card bb-category';a.href='items.html?category='+c.id;const icon=document.createElement('span');icon.className='bb-category-icon';icon.textContent=c.icon;const text=document.createElement('div');const name=document.createElement('strong');name.textContent=c.name;const count=document.createElement('small');count.textContent=`${c.item_count} active item${Number(c.item_count)===1?'':'s'}`;text.append(name,count);a.append(icon,text);return a}
function itemCard(i){const d=document.createElement('div');d.className='card p-3';const tag=document.createElement('div');tag.className='bb-eyebrow mb-2';tag.textContent=i.category.name;const h=document.createElement('h3');h.className='h5 fw-bold';h.textContent=i.name;const p=document.createElement('p');p.className='text-muted flex-grow-1';p.textContent=`${i.location} · ${i.rating.count?i.rating.avg+' ★':'No ratings yet'}`;const a=document.createElement('a');a.className='btn btn-outline-dark mt-auto';a.href='item.html?id='+i.id;a.textContent='View item';d.append(tag,h,p,a);return d}
async function loadHome(){
  try{const s=await fetch('/api/stats/public').then(r=>r.json());stats.textContent='';stats.append(stat('Community members',s.users),stat('Active items',s.items),stat('Completed borrows',s.completedBorrows))}catch{}
  try{const c=await fetch('/api/categories').then(r=>r.json());cats.textContent='';c.forEach(x=>cats.append(categoryCard(x)))}catch{cats.innerHTML='<div class="bb-empty">Categories will appear here when the server is available.</div>'}
  try{const r=await fetch('/api/items?limit=6').then(x=>x.json());recent.textContent='';r.items.forEach(x=>recent.append(itemCard(x)));if(!r.items.length)recent.innerHTML='<div class="bb-empty">No items have been listed yet.</div>'}catch{recent.innerHTML='<div class="bb-empty">Recently listed items are temporarily unavailable.</div>'}
  try{const data=await fetch('data/rules.json').then(r=>r.json());data.forEach(x=>{const li=document.createElement('li');li.textContent=x;rules.append(li)})}catch{}
  try{const data=await fetch('data/faq.json').then(r=>r.json());data.forEach((x,n)=>{const box=document.createElement('div');box.className='accordion-item';const id='faq'+n;const h=document.createElement('h2');h.className='accordion-header';const b=document.createElement('button');b.className='accordion-button collapsed';b.type='button';b.dataset.bsToggle='collapse';b.dataset.bsTarget='#'+id;b.textContent=x.q;const body=document.createElement('div');body.id=id;body.className='accordion-collapse collapse';const inner=document.createElement('div');inner.className='accordion-body';inner.textContent=x.a;h.append(b);body.append(inner);box.append(h,body);faq.append(box)})}catch{}
  const u=await getUser();if(u){heroSecondary.href='list-item.html';heroSecondary.textContent='List an item';bottomCta.href='dashboard.html';bottomCta.textContent='Open dashboard'}
}
loadHome();
