const express=require('express');
const helmet=require('helmet');
const {authLimit}=require('./middleware/rate');
const app=express();
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:'50kb'}));
app.use(express.static('client'));
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.use('/api/auth',authLimit,require('./routes/auth'));
app.use('/api',require('./routes/public'));
app.use('/api/items',require('./routes/items'));
app.use('/api/requests',require('./routes/requests'));
app.use('/api/wishlist',require('./routes/wishlist'));
app.use('/api/reviews',require('./routes/reviews'));
app.use('/api/users',require('./routes/users'));
app.use('/api/notifications',require('./routes/notifications'));
app.use('/api/me',require('./routes/me'));
app.use('/api/admin',require('./routes/admin'));
app.use('/api',(req,res)=>res.status(404).json({error:'Not found'}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Internal server error'})});
module.exports=app;
